services:
  - type: web
    name: neocare-backend
    env: python
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    buildCommand: pip install -r backend/requirements.txt
    rootDir: backend
